export const GET_COURSES = '@@COURSES/GET_COURSES'
export const GET_COURSES_SUCCESS = '@@COURSES/GET_COURSES_SUCCESS'
export const GET_COURSES_ERROR = '@@COURSES/GET_COURSES_ERROR'
export const GET_COURSES_LOADING = '@@COURSES/GET_COURSES_LOADING'
