export const GET_COURSES = '@@PLAYLIST/GET_COURSES'
export const GET_COURSES_SUCCESS = '@@PLAYLIST/GET_COURSES_SUCCESS'
export const GET_COURSES_ERROR = '@@PLAYLIST/GET_COURSES_ERROR'
export const GET_COURSES_LOADING = '@@PLAYLIST/GET_COURSES_LOADING'
